# [START app_yaml]
runtime: nodejs8

# [START env]
# The following env variables may contain sensitive information that grants
# anyone access to your database. Do not add this file to your source control.
env_variables:
  SQL_USER: postgres
  # SQL_PASSWORD: <password>
  SQL_DATABASE: postgres
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: hd-vendor-dev:us-east1:hd-vendor-postgres
# [END env]

# [START cloudsql_settings]
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: hd-vendor-dev:us-east1:hd-vendor-postgres
# [END cloudsql_settings]

service: graphql_daniel
# [END app_yaml]